# Generated by Django 4.0.2 on 2022-03-15 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_pledge_supporter_alter_project_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='goals',
            new_name='goal',
        ),
    ]
